- name: install darktable
  apt: pkg=darktable state=installed
  sudo: yes

- include: ../../base/tasks/favorites.yml item="application:\/\/darktable\.desktop"
  when: ansible_distribution_release == "trusty"
