- name: install devel tools
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
    - arduino
    - eagle # kicad
    - codeblocks
    - g++
    - gcc-avr
    - avr-libc
    - avrdude
    - cutecom
