- name: install dependencies for homesick
  apt: pkg=ruby1.9.1 state=installed
  sudo: yes

- name: check if rhc is already installed
  shell: gem list homesick | grep homesick
  register: homesick_check
  ignore_errors: True

- name: install homesick
  shell: gem install homesick
  when: homesick_check|failed
  sudo: yes

- include: pickled-vim.yml
#  when: homesick_check|failed
#
- include: dotfiles.yml
