- name: install dependencies for homesick
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
    - ruby1.9.1

- name: check if rhc is already installed
  shell: gem list homesick | grep homesick
  register: homesick_check
  ignore_errors: True

- name: install homesick
  shell: gem install homesick
  when: homesick_check|failed
  sudo: yes

- include: pickled-vim.yml
  when: homesick_check|failed
