- name: install devel tools
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
    - git
    - mercurial
    - subversion
    - sqlite3
    - python-dev
    - python-virtualenv
    - libmysqlclient-dev
    - libxml2-dev
    - libxslt1-dev
    - mysql-server
    - libffi-dev

# TODO: http://rajadileepkolli.wordpress.com/2011/12/25/how-to-install-sql-developer-in-ubuntu-and-run-as-app/

- name: create application launcher
  template: src=sqldeveloper.desktop.j2 dest="{{ home }}/.local/share/applications/sqldeveloper.desktop"

- include: ../../favorites/tasks/main.yml app='sqldeveloper.desktop' insert_after='sublime-text-2.desktop'

# TODO: https://launchpad.net/~couchdb/+archive/stable
