- name: install repository for Node.js
  apt_repository: repo='ppa:chris-lea/node.js' state=present update_cache=yes
  sudo: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'

- name: install Node.js
  apt: pkg=nodejs state=installed
  sudo: yes
