- name: ensure we have npm for {{ pkg }}
  shell: npm --version

- name: check if {{ pkg }} is already installed
  shell: npm -g list {{ pkg }} | grep {{ pkg }}
  register: pkg_check
  ignore_errors: True

- name: install {{ pkg }}
  shell: npm install -g {{ pkg }}
  when: pkg_check|failed
  sudo: yes
