- name: install dependencies for pickled-vim
  apt: pkg=exuberant-ctags state=installed
  sudo: yes

- name: use https:// instead of git://
  shell: git config --global url."https://".insteadOf git://

- name: clone pickled-vim repo
  shell: homesick clone git://github.com/leandrocosta/pickled-vim.git

- name: link dotfiles for pickled-vim
  shell: homesick symlink pickled-vim
