- name: check if R is already installed
  shell: R --version
  register: r_check
  ignore_errors: True

# http://cran.r-project.org/bin/linux/ubuntu/README

- name: download key for R's repository
  shell: gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E084DAB9
  when: r_check|failed
  sudo: yes

- name: install key for R's repository
  shell: sudo gpg -a --export E084DAB9 | sudo apt-key add -
  when: r_check|failed
  sudo: yes

- name: add repository for R
  lineinfile: dest=/etc/apt/sources.list.d/r-project.list create=yes regexp="^deb" line="deb http://cran.cnr.berkeley.edu/bin/linux/ubuntu {{ ansible_distribution_release }}/"
  when: r_check|failed
  sudo: yes

- name: install R
  apt: pkg=r-base state=installed update_cache=yes
  when: r_check|failed
  sudo: yes

- name: check if RStudio is already installed
  shell: dpkg -l | grep rstudio
  register: rstudio_check
  ignore_errors: True

- name: download RStudio
  get_url: url="http://download1.rstudio.org/rstudio-0.98.507-{{ ansible_architecture }}.deb" dest="/tmp/rstudio-0.98.507-{{ ansible_architecture }}.deb"
  when: rstudio_check|failed

- name: install dependencies for RStudio
  apt: pkg=libjpeg62 state=installed
  when: rstudio_check|failed
  sudo: yes

- name: install RStudio
  shell: dpkg -i "/tmp/rstudio-0.98.507-{{ ansible_architecture }}.deb"
  when: rstudio_check|failed
  sudo: yes

- name: check if RStudio is already in sidebar's favorites
  shell: gsettings get com.canonical.Unity.Launcher favorites | grep rstudio\.desktop
  register: rstfav_check
  ignore_errors: True

- name: put RStudio in sidebar's favorites
  shell: gsettings set com.canonical.Unity.Launcher favorites "`gsettings get com.canonical.Unity.Launcher favorites | sed -e \"s/\[/\['rstudio\.desktop', /g\"`"
  when: rstfav_check|failed
