- name: check if R is already installed
  shell: R --version
  register: r_check
  ignore_errors: True

# http://cran.r-project.org/bin/linux/ubuntu/README

- name: download key for R's repository
  shell: gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E084DAB9
  when: r_check|failed
  sudo: yes

- name: install key for R's repository
  shell: sudo gpg -a --export E084DAB9 | sudo apt-key add -
  when: r_check|failed
  sudo: yes

- name: add repository for R
  lineinfile: dest=/etc/apt/sources.list.d/r-project.list create=yes regexp="^deb" line="deb http://cran.cnr.berkeley.edu/bin/linux/ubuntu {{ ansible_distribution_release }}/"
  when: r_check|failed
  sudo: yes

- name: install R
  apt: pkg=r-base state=installed update_cache=yes
  when: r_check|failed
  sudo: yes

- name: check if RStudio is already installed
  shell: dpkg -l | grep rstudio
  register: rstudio_check
  ignore_errors: True

- name: install dependencies for RStudio
  apt: pkg=libjpeg62 state=installed
  when: rstudio_check|failed
  sudo: yes

- include: r-studio_i386.yml
  when: rstudio_check|failed and ansible_architecture == "i386"

- include: r-studio_amd64.yml
  when: rstudio_check|failed and ansible_architecture == "x86_64"

- include: favorites.yml item="application:\/\/rstudio\.desktop"
  when: ansible_distribution_release == "trusty"

- include: favorites.yml item="rstudio\.desktop"
  when: ansible_distribution_release == "precise"
