- name: check if rhc is already installed
  shell: gem list rhc | grep rhc
  register: rhc_check
  ignore_errors: True

- name: install requirements for rhc
  apt: pkg={{ item }} state=installed
  with_items:
    - ruby1.9.1
  when: rhc_check|failed
  sudo: yes

- name: install rhc
  shell: gem install rhc
  when: rhc_check|failed
  sudo: yes
