- name: check if SourceCodePro is already installed
  shell: fc-list | grep "Source Code Pro"
  register: sourcecodepro_check
  ignore_errors: True

- name: download SourceCodePro
  get_url: url=http://downloads.sourceforge.net/project/sourcecodepro.adobe/SourceCodePro_FontsOnly-1.017.zip dest=/tmp/SourceCodePro_FontsOnly-1.017.zip
  when: sourcecodepro_check|failed

- name: unpack SourceCodePro
  shell: unzip -o -j /tmp/SourceCodePro_FontsOnly-1.017.zip "SourceCodePro_FontsOnly-1.017/OTF/*.otf" -d "{{ home }}/.fonts/"
  when: sourcecodepro_check|failed

- name: update font cache
  shell: fc-cache -f -v
  sudo: yes
  when: sourcecodepro_check|failed
