- name: check if Vagrant is already installed
  shell: vagrant -v
  register: vgt_exists
  ignore_errors: True

- name: download Vagrant
  get_url: url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.3_i686.deb dest=/tmp/vagrant_1.6.3_i686.deb
  when: vgt_exists.rc !=0

- name: install Vagrant
  command: dpkg -i /tmp/vagrant_1.6.3_i686.deb
  when: vgt_exists.rc !=0
  sudo: yes
