- name: check if WinMerge is already installed
#  stat: path="{{ home }}/.wine/drive_c/Program Files/WinMerge"
  stat: path="{{ winmerge_path }}"
  register: winmerge_check
#  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: show winmerge_check register
  debug: msg={{ winmerge_check.stat.exists }}

#- name: check if WinMerge is already installed
#  stat: path="{{ home }}/.local/share/applications/wine-extension-winmerge.desktop"
#  register: winmerge_check
#  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'

- name: install requirements for WinMerge
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
    - wine
  when: winmerge_check.stat.exists == False

- name: download WinMerge
  get_url: url=http://downloads.sourceforge.net/project/winmerge/stable/2.14.0/WinMerge-2.14.0-Setup.exe dest=/tmp/WinMerge-2.14.0-Setup.exe
  when: winmerge_check.stat.exists == False

- name: install WinMerge
  command: wine /tmp/WinMerge-2.14.0-Setup.exe
  when: winmerge_check.stat.exists == False
  ignore_errors: True
