- hosts: localhost
  vars:
    - { home: "{{ lookup('env','HOME') }}" }
  vars_files:
#    - [ "vars/{{ lookup('env', 'LANGUAGE') }}.yml", "vars/default.yml" ]
    - [ "vars/default.yml" ]
  roles:
    - base
    #- photo
    #- video
    #- devel
    #- brew
