#winmerge_path: "{{ home }}/.wine/drive_c/Program Files/WinMerge"
winmerge_path: "{{ home }}/.wine/drive_c/Program Files (x86)/WinMerge"

sqldeveloper_exec: "{{ home }}/opt/sqldeveloper/sqldeveloper.sh"
sqldeveloper_icon: "{{ home }}/opt/sqldeveloper/icon.png"
