- name: check if Google Chrome is already installed
  shell: dpkg -l | grep google-chrome-stable
  register: gchrome_check
  ignore_errors: True

# http://www.howopensource.com/2011/10/install-google-chrome-in-ubuntu-11-10-11-04-10-10-10-04/

- name: install key for Google Chrome
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  sudo: yes
  when: gchrome_check|failed

- name: add repository for Google Chrome
  shell: sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  sudo: yes
  when: gchrome_check|failed

- name: install Google Chrome
  apt: pkg=google-chrome-stable state=installed update_cache=yes
  sudo: yes
  when: gchrome_check|failed

- include: favorites.yml item="application:\/\/google-chrome\.desktop"
  when: ansible_distribution_release == "trusty"

- include: favorites.yml item="google-chrome\.desktop"
  when: ansible_distribution_release == "precise"
