- name: check if java8 is already installed
  stat: path=/usr/lib/jvm/java-8-oracle
  register: java8_path

- name: add repository for java8
  apt_repository: repo='ppa:webupd8team/java' state=present update_cache=yes
  sudo: yes
  when: java8_path.stat.exists == False

- name: automatically select the Oracle License
  #shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  sudo: yes

- name: install java8
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
    - oracle-java8-installer
  when: java8_path.stat.exists == False
