- name: install base tools
  apt: pkg={{ item }} state=installed
  with_items:
    - vim
    - tree
    - htop
    - curl
    - p7zip
    - unrar
    - ack-grep
    - wavemon
    - mpg123
    - vlc
    - nfs-common
    - quodlibet
    - nautilus-dropbox
  sudo: yes
