- name: check if hadoop is already installed
  stat: path={{ home }}/opt/hadoop-2.4.1
  register: hadoop_path

- name: download Hadoop
  get_url: url=http://ftp.unicamp.br/pub/apache/hadoop/common/hadoop-2.4.1/hadoop-2.4.1.tar.gz dest=/tmp/hadoop-2.4.1.tar.gz
  when: hadoop_path.stat.exists == False

- name: unpack Hadoop
  unarchive: src=/tmp/hadoop-2.4.1.tar.gz dest="{{ home }}/opt"
  when: hadoop_path.stat.exists == False

- name: create link
  file: dest="{{ home }}/opt/hadoop" src="{{ home }}/opt/hadoop-2.4.1" state=link

- name: add Hadoop env vars to .profile
  lineinfile: dest={{ home }}/.profile line="{{ item }}"
  with_items:
    - export HADOOP_INSTALL={{ home }}/opt/hadoop
    - export PATH=\"$PATH:$HADOOP_INSTALL/bin\"
    - export PATH=\"$PATH:$HADOOP_INSTALL/sbin\"
    - export HADOOP_MAPRED_HOME=\"$HADOOP_INSTALL\"
    - export HADOOP_COMMON_HOME=\"$HADOOP_INSTALL\"
    - export HADOOP_HDFS_HOME=\"$HADOOP_INSTALL\"
    - export YARN_HOME=\"$HADOOP_INSTALL\"

- name: add Hadoop env vars to .zshrc
  lineinfile: dest={{ home }}/.zshrc line="{{ item }}"
  with_items:
    - export HADOOP_INSTALL={{ home }}/opt/hadoop
    - export PATH=\"$PATH:$HADOOP_INSTALL/bin\"
    - export PATH=\"$PATH:$HADOOP_INSTALL/sbin\"
    - export HADOOP_MAPRED_HOME=\"$HADOOP_INSTALL\"
    - export HADOOP_COMMON_HOME=\"$HADOOP_INSTALL\"
    - export HADOOP_HDFS_HOME=\"$HADOOP_INSTALL\"
    - export YARN_HOME=\"$HADOOP_INSTALL\"

- name: add JAVA_HOME to hadoop-env.sh
  lineinfile: dest="{{ home }}/opt/hadoop/etc/hadoop/hadoop-env.sh" line="export JAVA_HOME=/usr/lib/jvm/jdk1.7.0_65" regexp="^export JAVA_HOME=" 

- name: add core-site.xml
  template: src=core-site.xml.j2 dest="{{ home }}/opt/hadoop/etc/hadoop/core-site.xml"

- name: add yarn-site.xml
  template: src=yarn-site.xml.j2 dest="{{ home }}/opt/hadoop/etc/hadoop/yarn-site.xml"

- name: add mapred-site.xml
  template: src=mapred-site.xml.j2 dest="{{ home }}/opt/hadoop/etc/hadoop/mapred-site.xml"

- name: add hdfs-site.xml
  template: src=hdfs-site.xml.j2 dest="{{ home }}/opt/hadoop/etc/hadoop/hdfs-site.xml"
